// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: compaction_data.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#ifndef GRPC_compaction_5fdata_2eproto__INCLUDED
#define GRPC_compaction_5fdata_2eproto__INCLUDED

#include "compaction_data.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace compaction_data {

// The greeting service definition.
class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "compaction_data.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::compaction_data::CompactionReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CompactionReply>> AsyncSayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CompactionReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CompactionReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CompactionReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    virtual ::grpc::Status Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::compaction_data::CacheReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CacheReply>> AsyncCaching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CacheReply>>(AsyncCachingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CacheReply>> PrepareAsyncCaching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CacheReply>>(PrepareAsyncCachingRaw(context, request, cq));
    }
    virtual ::grpc::Status LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::compaction_data::LocalCompactionReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::LocalCompactionReply>> AsyncLocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::LocalCompactionReply>>(AsyncLocalCompactionResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::LocalCompactionReply>> PrepareAsyncLocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::LocalCompactionReply>>(PrepareAsyncLocalCompactionResultRaw(context, request, cq));
    }
    virtual ::grpc::Status PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::compaction_data::PingTestReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PingTestReply>> AsyncPingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PingTestReply>>(AsyncPingTestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PingTestReply>> PrepareAsyncPingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PingTestReply>>(PrepareAsyncPingTestRaw(context, request, cq));
    }
    virtual ::grpc::Status Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::compaction_data::TokenReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::TokenReply>> AsyncToken(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::TokenReply>>(AsyncTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::TokenReply>> PrepareAsyncToken(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::TokenReply>>(PrepareAsyncTokenRaw(context, request, cq));
    }
    virtual ::grpc::Status Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::compaction_data::PreprocessReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PreprocessReply>> AsyncPreprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PreprocessReply>>(AsyncPreprocessRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PreprocessReply>> PrepareAsyncPreprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PreprocessReply>>(PrepareAsyncPreprocessRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      virtual void SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CompactionReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CompactionReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CacheReply>* AsyncCachingRaw(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::CacheReply>* PrepareAsyncCachingRaw(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::LocalCompactionReply>* AsyncLocalCompactionResultRaw(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::LocalCompactionReply>* PrepareAsyncLocalCompactionResultRaw(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PingTestReply>* AsyncPingTestRaw(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PingTestReply>* PrepareAsyncPingTestRaw(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::TokenReply>* AsyncTokenRaw(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::TokenReply>* PrepareAsyncTokenRaw(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PreprocessReply>* AsyncPreprocessRaw(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::compaction_data::PreprocessReply>* PrepareAsyncPreprocessRaw(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::compaction_data::CompactionReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::CompactionReply>> AsyncSayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::CompactionReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::CompactionReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::CompactionReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    ::grpc::Status Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::compaction_data::CacheReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::CacheReply>> AsyncCaching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::CacheReply>>(AsyncCachingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::CacheReply>> PrepareAsyncCaching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::CacheReply>>(PrepareAsyncCachingRaw(context, request, cq));
    }
    ::grpc::Status LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::compaction_data::LocalCompactionReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::LocalCompactionReply>> AsyncLocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::LocalCompactionReply>>(AsyncLocalCompactionResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::LocalCompactionReply>> PrepareAsyncLocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::LocalCompactionReply>>(PrepareAsyncLocalCompactionResultRaw(context, request, cq));
    }
    ::grpc::Status PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::compaction_data::PingTestReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::PingTestReply>> AsyncPingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::PingTestReply>>(AsyncPingTestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::PingTestReply>> PrepareAsyncPingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::PingTestReply>>(PrepareAsyncPingTestRaw(context, request, cq));
    }
    ::grpc::Status Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::compaction_data::TokenReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::TokenReply>> AsyncToken(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::TokenReply>>(AsyncTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::TokenReply>> PrepareAsyncToken(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::TokenReply>>(PrepareAsyncTokenRaw(context, request, cq));
    }
    ::grpc::Status Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::compaction_data::PreprocessReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::PreprocessReply>> AsyncPreprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::PreprocessReply>>(AsyncPreprocessRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::PreprocessReply>> PrepareAsyncPreprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::compaction_data::PreprocessReply>>(PrepareAsyncPreprocessRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::compaction_data::CompactionReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::CompactionReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::CacheReply>* AsyncCachingRaw(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::CacheReply>* PrepareAsyncCachingRaw(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::LocalCompactionReply>* AsyncLocalCompactionResultRaw(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::LocalCompactionReply>* PrepareAsyncLocalCompactionResultRaw(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::PingTestReply>* AsyncPingTestRaw(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::PingTestReply>* PrepareAsyncPingTestRaw(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::TokenReply>* AsyncTokenRaw(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::TokenReply>* PrepareAsyncTokenRaw(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::PreprocessReply>* AsyncPreprocessRaw(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::compaction_data::PreprocessReply>* PrepareAsyncPreprocessRaw(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
    const ::grpc::internal::RpcMethod rpcmethod_Caching_;
    const ::grpc::internal::RpcMethod rpcmethod_LocalCompactionResult_;
    const ::grpc::internal::RpcMethod rpcmethod_PingTest_;
    const ::grpc::internal::RpcMethod rpcmethod_Token_;
    const ::grpc::internal::RpcMethod rpcmethod_Preprocess_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response);
    virtual ::grpc::Status Caching(::grpc::ServerContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response);
    virtual ::grpc::Status LocalCompactionResult(::grpc::ServerContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response);
    virtual ::grpc::Status PingTest(::grpc::ServerContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response);
    virtual ::grpc::Status Token(::grpc::ServerContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response);
    virtual ::grpc::Status Preprocess(::grpc::ServerContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::compaction_data::CompactionRequest* /*request*/, ::compaction_data::CompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::compaction_data::CompactionRequest* request, ::grpc::ServerAsyncResponseWriter< ::compaction_data::CompactionReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Caching : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Caching() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Caching() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Caching(::grpc::ServerContext* /*context*/, const ::compaction_data::CacheRequest* /*request*/, ::compaction_data::CacheReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCaching(::grpc::ServerContext* context, ::compaction_data::CacheRequest* request, ::grpc::ServerAsyncResponseWriter< ::compaction_data::CacheReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_LocalCompactionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_LocalCompactionResult() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_LocalCompactionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LocalCompactionResult(::grpc::ServerContext* /*context*/, const ::compaction_data::LocalCompactionRequest* /*request*/, ::compaction_data::LocalCompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLocalCompactionResult(::grpc::ServerContext* context, ::compaction_data::LocalCompactionRequest* request, ::grpc::ServerAsyncResponseWriter< ::compaction_data::LocalCompactionReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PingTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PingTest() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_PingTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingTest(::grpc::ServerContext* /*context*/, const ::compaction_data::PingTestRequest* /*request*/, ::compaction_data::PingTestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPingTest(::grpc::ServerContext* context, ::compaction_data::PingTestRequest* request, ::grpc::ServerAsyncResponseWriter< ::compaction_data::PingTestReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Token : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Token() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_Token() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Token(::grpc::ServerContext* /*context*/, const ::compaction_data::TokenRequest* /*request*/, ::compaction_data::TokenReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestToken(::grpc::ServerContext* context, ::compaction_data::TokenRequest* request, ::grpc::ServerAsyncResponseWriter< ::compaction_data::TokenReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Preprocess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Preprocess() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_Preprocess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Preprocess(::grpc::ServerContext* /*context*/, const ::compaction_data::PreprocessRequest* /*request*/, ::compaction_data::PreprocessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPreprocess(::grpc::ServerContext* context, ::compaction_data::PreprocessRequest* request, ::grpc::ServerAsyncResponseWriter< ::compaction_data::PreprocessReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<WithAsyncMethod_Caching<WithAsyncMethod_LocalCompactionResult<WithAsyncMethod_PingTest<WithAsyncMethod_Token<WithAsyncMethod_Preprocess<Service > > > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SayHello() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::compaction_data::CompactionRequest, ::compaction_data::CompactionReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response) { return this->SayHello(context, request, response); }));}
    void SetMessageAllocatorFor_SayHello(
        ::grpc::experimental::MessageAllocator< ::compaction_data::CompactionRequest, ::compaction_data::CompactionReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::compaction_data::CompactionRequest, ::compaction_data::CompactionReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::compaction_data::CompactionRequest* /*request*/, ::compaction_data::CompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::compaction_data::CompactionRequest* /*request*/, ::compaction_data::CompactionReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SayHello(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::compaction_data::CompactionRequest* /*request*/, ::compaction_data::CompactionReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Caching : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Caching() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::compaction_data::CacheRequest, ::compaction_data::CacheReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response) { return this->Caching(context, request, response); }));}
    void SetMessageAllocatorFor_Caching(
        ::grpc::experimental::MessageAllocator< ::compaction_data::CacheRequest, ::compaction_data::CacheReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::compaction_data::CacheRequest, ::compaction_data::CacheReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Caching() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Caching(::grpc::ServerContext* /*context*/, const ::compaction_data::CacheRequest* /*request*/, ::compaction_data::CacheReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Caching(
      ::grpc::CallbackServerContext* /*context*/, const ::compaction_data::CacheRequest* /*request*/, ::compaction_data::CacheReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Caching(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::compaction_data::CacheRequest* /*request*/, ::compaction_data::CacheReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_LocalCompactionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_LocalCompactionResult() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::compaction_data::LocalCompactionRequest, ::compaction_data::LocalCompactionReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response) { return this->LocalCompactionResult(context, request, response); }));}
    void SetMessageAllocatorFor_LocalCompactionResult(
        ::grpc::experimental::MessageAllocator< ::compaction_data::LocalCompactionRequest, ::compaction_data::LocalCompactionReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::compaction_data::LocalCompactionRequest, ::compaction_data::LocalCompactionReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_LocalCompactionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LocalCompactionResult(::grpc::ServerContext* /*context*/, const ::compaction_data::LocalCompactionRequest* /*request*/, ::compaction_data::LocalCompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* LocalCompactionResult(
      ::grpc::CallbackServerContext* /*context*/, const ::compaction_data::LocalCompactionRequest* /*request*/, ::compaction_data::LocalCompactionReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* LocalCompactionResult(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::compaction_data::LocalCompactionRequest* /*request*/, ::compaction_data::LocalCompactionReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PingTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PingTest() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::compaction_data::PingTestRequest, ::compaction_data::PingTestReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response) { return this->PingTest(context, request, response); }));}
    void SetMessageAllocatorFor_PingTest(
        ::grpc::experimental::MessageAllocator< ::compaction_data::PingTestRequest, ::compaction_data::PingTestReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::compaction_data::PingTestRequest, ::compaction_data::PingTestReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_PingTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingTest(::grpc::ServerContext* /*context*/, const ::compaction_data::PingTestRequest* /*request*/, ::compaction_data::PingTestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PingTest(
      ::grpc::CallbackServerContext* /*context*/, const ::compaction_data::PingTestRequest* /*request*/, ::compaction_data::PingTestReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PingTest(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::compaction_data::PingTestRequest* /*request*/, ::compaction_data::PingTestReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Token : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Token() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::compaction_data::TokenRequest, ::compaction_data::TokenReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response) { return this->Token(context, request, response); }));}
    void SetMessageAllocatorFor_Token(
        ::grpc::experimental::MessageAllocator< ::compaction_data::TokenRequest, ::compaction_data::TokenReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(4);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::compaction_data::TokenRequest, ::compaction_data::TokenReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Token() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Token(::grpc::ServerContext* /*context*/, const ::compaction_data::TokenRequest* /*request*/, ::compaction_data::TokenReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Token(
      ::grpc::CallbackServerContext* /*context*/, const ::compaction_data::TokenRequest* /*request*/, ::compaction_data::TokenReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Token(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::compaction_data::TokenRequest* /*request*/, ::compaction_data::TokenReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Preprocess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Preprocess() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::compaction_data::PreprocessRequest, ::compaction_data::PreprocessReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response) { return this->Preprocess(context, request, response); }));}
    void SetMessageAllocatorFor_Preprocess(
        ::grpc::experimental::MessageAllocator< ::compaction_data::PreprocessRequest, ::compaction_data::PreprocessReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(5);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::compaction_data::PreprocessRequest, ::compaction_data::PreprocessReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Preprocess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Preprocess(::grpc::ServerContext* /*context*/, const ::compaction_data::PreprocessRequest* /*request*/, ::compaction_data::PreprocessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Preprocess(
      ::grpc::CallbackServerContext* /*context*/, const ::compaction_data::PreprocessRequest* /*request*/, ::compaction_data::PreprocessReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Preprocess(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::compaction_data::PreprocessRequest* /*request*/, ::compaction_data::PreprocessReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SayHello<ExperimentalWithCallbackMethod_Caching<ExperimentalWithCallbackMethod_LocalCompactionResult<ExperimentalWithCallbackMethod_PingTest<ExperimentalWithCallbackMethod_Token<ExperimentalWithCallbackMethod_Preprocess<Service > > > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SayHello<ExperimentalWithCallbackMethod_Caching<ExperimentalWithCallbackMethod_LocalCompactionResult<ExperimentalWithCallbackMethod_PingTest<ExperimentalWithCallbackMethod_Token<ExperimentalWithCallbackMethod_Preprocess<Service > > > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::compaction_data::CompactionRequest* /*request*/, ::compaction_data::CompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Caching : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Caching() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Caching() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Caching(::grpc::ServerContext* /*context*/, const ::compaction_data::CacheRequest* /*request*/, ::compaction_data::CacheReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_LocalCompactionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_LocalCompactionResult() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_LocalCompactionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LocalCompactionResult(::grpc::ServerContext* /*context*/, const ::compaction_data::LocalCompactionRequest* /*request*/, ::compaction_data::LocalCompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PingTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PingTest() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_PingTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingTest(::grpc::ServerContext* /*context*/, const ::compaction_data::PingTestRequest* /*request*/, ::compaction_data::PingTestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Token : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Token() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_Token() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Token(::grpc::ServerContext* /*context*/, const ::compaction_data::TokenRequest* /*request*/, ::compaction_data::TokenReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Preprocess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Preprocess() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_Preprocess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Preprocess(::grpc::ServerContext* /*context*/, const ::compaction_data::PreprocessRequest* /*request*/, ::compaction_data::PreprocessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::compaction_data::CompactionRequest* /*request*/, ::compaction_data::CompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Caching : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Caching() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Caching() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Caching(::grpc::ServerContext* /*context*/, const ::compaction_data::CacheRequest* /*request*/, ::compaction_data::CacheReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCaching(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_LocalCompactionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_LocalCompactionResult() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_LocalCompactionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LocalCompactionResult(::grpc::ServerContext* /*context*/, const ::compaction_data::LocalCompactionRequest* /*request*/, ::compaction_data::LocalCompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLocalCompactionResult(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PingTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PingTest() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_PingTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingTest(::grpc::ServerContext* /*context*/, const ::compaction_data::PingTestRequest* /*request*/, ::compaction_data::PingTestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPingTest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Token : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Token() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_Token() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Token(::grpc::ServerContext* /*context*/, const ::compaction_data::TokenRequest* /*request*/, ::compaction_data::TokenReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestToken(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Preprocess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Preprocess() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_Preprocess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Preprocess(::grpc::ServerContext* /*context*/, const ::compaction_data::PreprocessRequest* /*request*/, ::compaction_data::PreprocessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPreprocess(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SayHello() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHello(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::compaction_data::CompactionRequest* /*request*/, ::compaction_data::CompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SayHello(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Caching : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Caching() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Caching(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Caching() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Caching(::grpc::ServerContext* /*context*/, const ::compaction_data::CacheRequest* /*request*/, ::compaction_data::CacheReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Caching(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Caching(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_LocalCompactionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_LocalCompactionResult() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->LocalCompactionResult(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_LocalCompactionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LocalCompactionResult(::grpc::ServerContext* /*context*/, const ::compaction_data::LocalCompactionRequest* /*request*/, ::compaction_data::LocalCompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* LocalCompactionResult(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* LocalCompactionResult(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PingTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PingTest() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PingTest(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PingTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingTest(::grpc::ServerContext* /*context*/, const ::compaction_data::PingTestRequest* /*request*/, ::compaction_data::PingTestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PingTest(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PingTest(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Token : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Token() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Token(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Token() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Token(::grpc::ServerContext* /*context*/, const ::compaction_data::TokenRequest* /*request*/, ::compaction_data::TokenReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Token(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Token(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Preprocess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Preprocess() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Preprocess(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Preprocess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Preprocess(::grpc::ServerContext* /*context*/, const ::compaction_data::PreprocessRequest* /*request*/, ::compaction_data::PreprocessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Preprocess(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Preprocess(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::compaction_data::CompactionRequest, ::compaction_data::CompactionReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::compaction_data::CompactionRequest, ::compaction_data::CompactionReply>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::compaction_data::CompactionRequest* /*request*/, ::compaction_data::CompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::compaction_data::CompactionRequest,::compaction_data::CompactionReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Caching : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Caching() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::compaction_data::CacheRequest, ::compaction_data::CacheReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::compaction_data::CacheRequest, ::compaction_data::CacheReply>* streamer) {
                       return this->StreamedCaching(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Caching() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Caching(::grpc::ServerContext* /*context*/, const ::compaction_data::CacheRequest* /*request*/, ::compaction_data::CacheReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCaching(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::compaction_data::CacheRequest,::compaction_data::CacheReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_LocalCompactionResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_LocalCompactionResult() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::compaction_data::LocalCompactionRequest, ::compaction_data::LocalCompactionReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::compaction_data::LocalCompactionRequest, ::compaction_data::LocalCompactionReply>* streamer) {
                       return this->StreamedLocalCompactionResult(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_LocalCompactionResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status LocalCompactionResult(::grpc::ServerContext* /*context*/, const ::compaction_data::LocalCompactionRequest* /*request*/, ::compaction_data::LocalCompactionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLocalCompactionResult(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::compaction_data::LocalCompactionRequest,::compaction_data::LocalCompactionReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PingTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PingTest() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::compaction_data::PingTestRequest, ::compaction_data::PingTestReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::compaction_data::PingTestRequest, ::compaction_data::PingTestReply>* streamer) {
                       return this->StreamedPingTest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PingTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PingTest(::grpc::ServerContext* /*context*/, const ::compaction_data::PingTestRequest* /*request*/, ::compaction_data::PingTestReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPingTest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::compaction_data::PingTestRequest,::compaction_data::PingTestReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Token : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Token() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::compaction_data::TokenRequest, ::compaction_data::TokenReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::compaction_data::TokenRequest, ::compaction_data::TokenReply>* streamer) {
                       return this->StreamedToken(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Token() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Token(::grpc::ServerContext* /*context*/, const ::compaction_data::TokenRequest* /*request*/, ::compaction_data::TokenReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedToken(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::compaction_data::TokenRequest,::compaction_data::TokenReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Preprocess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Preprocess() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::compaction_data::PreprocessRequest, ::compaction_data::PreprocessReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::compaction_data::PreprocessRequest, ::compaction_data::PreprocessReply>* streamer) {
                       return this->StreamedPreprocess(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Preprocess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Preprocess(::grpc::ServerContext* /*context*/, const ::compaction_data::PreprocessRequest* /*request*/, ::compaction_data::PreprocessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPreprocess(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::compaction_data::PreprocessRequest,::compaction_data::PreprocessReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_Caching<WithStreamedUnaryMethod_LocalCompactionResult<WithStreamedUnaryMethod_PingTest<WithStreamedUnaryMethod_Token<WithStreamedUnaryMethod_Preprocess<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_Caching<WithStreamedUnaryMethod_LocalCompactionResult<WithStreamedUnaryMethod_PingTest<WithStreamedUnaryMethod_Token<WithStreamedUnaryMethod_Preprocess<Service > > > > > > StreamedService;
};

}  // namespace compaction_data


#endif  // GRPC_compaction_5fdata_2eproto__INCLUDED
