// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: compaction_data.proto

#include "compaction_data.pb.h"
#include "compaction_data.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace compaction_data {

static const char* Greeter_method_names[] = {
  "/compaction_data.Greeter/SayHello",
  "/compaction_data.Greeter/Caching",
  "/compaction_data.Greeter/LocalCompactionResult",
  "/compaction_data.Greeter/PingTest",
  "/compaction_data.Greeter/Token",
  "/compaction_data.Greeter/Preprocess",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(Greeter_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Caching_(Greeter_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LocalCompactionResult_(Greeter_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PingTest_(Greeter_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Token_(Greeter_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Preprocess_(Greeter_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeter::Stub::SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::compaction_data::CompactionReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::compaction_data::CompactionRequest, ::compaction_data::CompactionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Greeter::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::compaction_data::CompactionRequest, ::compaction_data::CompactionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::CompactionReply>* Greeter::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::compaction_data::CompactionReply, ::compaction_data::CompactionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::CompactionReply>* Greeter::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::compaction_data::CompactionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::compaction_data::CacheReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::compaction_data::CacheRequest, ::compaction_data::CacheReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Caching_, context, request, response);
}

void Greeter::Stub::experimental_async::Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::compaction_data::CacheRequest, ::compaction_data::CacheReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Caching_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::Caching(::grpc::ClientContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Caching_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::CacheReply>* Greeter::Stub::PrepareAsyncCachingRaw(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::compaction_data::CacheReply, ::compaction_data::CacheRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Caching_, context, request);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::CacheReply>* Greeter::Stub::AsyncCachingRaw(::grpc::ClientContext* context, const ::compaction_data::CacheRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCachingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::compaction_data::LocalCompactionReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::compaction_data::LocalCompactionRequest, ::compaction_data::LocalCompactionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LocalCompactionResult_, context, request, response);
}

void Greeter::Stub::experimental_async::LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::compaction_data::LocalCompactionRequest, ::compaction_data::LocalCompactionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LocalCompactionResult_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::LocalCompactionResult(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LocalCompactionResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::LocalCompactionReply>* Greeter::Stub::PrepareAsyncLocalCompactionResultRaw(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::compaction_data::LocalCompactionReply, ::compaction_data::LocalCompactionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LocalCompactionResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::LocalCompactionReply>* Greeter::Stub::AsyncLocalCompactionResultRaw(::grpc::ClientContext* context, const ::compaction_data::LocalCompactionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLocalCompactionResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::compaction_data::PingTestReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::compaction_data::PingTestRequest, ::compaction_data::PingTestReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PingTest_, context, request, response);
}

void Greeter::Stub::experimental_async::PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::compaction_data::PingTestRequest, ::compaction_data::PingTestReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PingTest_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::PingTest(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PingTest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::PingTestReply>* Greeter::Stub::PrepareAsyncPingTestRaw(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::compaction_data::PingTestReply, ::compaction_data::PingTestRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PingTest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::PingTestReply>* Greeter::Stub::AsyncPingTestRaw(::grpc::ClientContext* context, const ::compaction_data::PingTestRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingTestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::compaction_data::TokenReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::compaction_data::TokenRequest, ::compaction_data::TokenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Token_, context, request, response);
}

void Greeter::Stub::experimental_async::Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::compaction_data::TokenRequest, ::compaction_data::TokenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Token_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::Token(::grpc::ClientContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Token_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::TokenReply>* Greeter::Stub::PrepareAsyncTokenRaw(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::compaction_data::TokenReply, ::compaction_data::TokenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Token_, context, request);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::TokenReply>* Greeter::Stub::AsyncTokenRaw(::grpc::ClientContext* context, const ::compaction_data::TokenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::compaction_data::PreprocessReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::compaction_data::PreprocessRequest, ::compaction_data::PreprocessReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Preprocess_, context, request, response);
}

void Greeter::Stub::experimental_async::Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::compaction_data::PreprocessRequest, ::compaction_data::PreprocessReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Preprocess_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::Preprocess(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Preprocess_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::PreprocessReply>* Greeter::Stub::PrepareAsyncPreprocessRaw(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::compaction_data::PreprocessReply, ::compaction_data::PreprocessRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Preprocess_, context, request);
}

::grpc::ClientAsyncResponseReader< ::compaction_data::PreprocessReply>* Greeter::Stub::AsyncPreprocessRaw(::grpc::ClientContext* context, const ::compaction_data::PreprocessRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPreprocessRaw(context, request, cq);
  result->StartCall();
  return result;
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::compaction_data::CompactionRequest, ::compaction_data::CompactionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::compaction_data::CompactionRequest* req,
             ::compaction_data::CompactionReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::compaction_data::CacheRequest, ::compaction_data::CacheReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::compaction_data::CacheRequest* req,
             ::compaction_data::CacheReply* resp) {
               return service->Caching(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::compaction_data::LocalCompactionRequest, ::compaction_data::LocalCompactionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::compaction_data::LocalCompactionRequest* req,
             ::compaction_data::LocalCompactionReply* resp) {
               return service->LocalCompactionResult(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::compaction_data::PingTestRequest, ::compaction_data::PingTestReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::compaction_data::PingTestRequest* req,
             ::compaction_data::PingTestReply* resp) {
               return service->PingTest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::compaction_data::TokenRequest, ::compaction_data::TokenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::compaction_data::TokenRequest* req,
             ::compaction_data::TokenReply* resp) {
               return service->Token(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::compaction_data::PreprocessRequest, ::compaction_data::PreprocessReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::compaction_data::PreprocessRequest* req,
             ::compaction_data::PreprocessReply* resp) {
               return service->Preprocess(ctx, req, resp);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SayHello(::grpc::ServerContext* context, const ::compaction_data::CompactionRequest* request, ::compaction_data::CompactionReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::Caching(::grpc::ServerContext* context, const ::compaction_data::CacheRequest* request, ::compaction_data::CacheReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::LocalCompactionResult(::grpc::ServerContext* context, const ::compaction_data::LocalCompactionRequest* request, ::compaction_data::LocalCompactionReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::PingTest(::grpc::ServerContext* context, const ::compaction_data::PingTestRequest* request, ::compaction_data::PingTestReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::Token(::grpc::ServerContext* context, const ::compaction_data::TokenRequest* request, ::compaction_data::TokenReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::Preprocess(::grpc::ServerContext* context, const ::compaction_data::PreprocessRequest* request, ::compaction_data::PreprocessReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace compaction_data

